version: '3.8'

services:
  web:
    image: ${DOCKER_REGISTRY}/${NEXT_APP_NAME}:latest
    container_name: libri-frontend
    restart: unless-stopped
    environment:
      - NODE_ENV=production
      - NEXT_TELEMETRY_DISABLED=1
      - NEXT_PUBLIC_API_URL=${NEXT_PUBLIC_API_URL}
    ports:
      - "3000:3000"
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:3000/"]
      interval: 30s
      timeout: 30s
      retries: 3
      start_period: 5s
    networks:
      - libri-network
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "3"

networks:
  libri-network:
    name: libri-network
    driver: bridge
